# Generated by Django 5.1.4 on 2025-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.IntegerField()),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("channels", models.IntegerField()),
            ],
            options={
                "db_table": "Images",
            },
        ),
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.IntegerField()),
                ("num_pages", models.IntegerField()),
                ("page_width", models.FloatField()),
                ("page_height", models.FloatField()),
            ],
            options={
                "db_table": "Pdfs",
            },
        ),
    ]
